### ISSUE TITLE
WHERE IS DA WEBSITE THO?

### ISSUE THREAD

**Issue by guruvamsi-policharla** [sankalpgaur/sankalpgaur.github.io#1]
bruh, can't see no website overhere

**Comment by sankalpgaur** [comment]
Wut website?

**Comment by guruvamsi-policharla** [comment]
The repository is called "My Personal Website".

**Comment by sankalpgaur** [comment]
Well, I had just created this thing to provide a link to my CV. I had forgotten that there exists the bighome.iitb thing.
